services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: taskapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    image: ghcr.io/daniahamed/apptraining-backend:latest
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: taskapp
      DB_USER: admin
      DB_PASSWORD: password123
    depends_on:
      - db

  frontend:
    image: ghcr.io/daniahamed/apptraining-frontend:latest
    ports:
      - "3001:3001"
    environment:
      REACT_APP_API_URL: http://localhost:3002
    depends_on:
      - backend


